{% set version = "0.1.0" %}

package:
  name: darts_bht
  version: {{ version }}

source:
  path: ../
  #md5sum: 45e4810189634c753507f753dda83a9a
  #url: https://github.com/zj-zhang/Darts_BHT/archive/v0.1.0.tar.gz


build:
  number: 4

requirements:
  build:
    - python=2.7
    - rpy2
    - r-base>=3.4.3
    - pandas
  run:
    - python=2.7
    - r-base>=3.4.3
    - pandas
    - rpy2


test:
  imports:
    - Darts_BHT.BHT_wrapper
    - Darts_BHT.rmats_wrapper
    - Darts_BHT.pretty_writter
  commands:
    - Darts_BHT -h
    - Darts_BHT rmats_count -h
    - Darts_BHT bayes_infer -h
